fixup! ASoC: SOF: sof-client: expose Zephyr GDB stub
SND_SOC_SOF_DEBUG_FW_GDB needs to depend on SND_SOC_SOF to avoid randconfig
which exhibits:
sound/soc/sof/sof-client-fw-gdb.o: in function `sof_fw_gdb_poll_work':
   sof-client-fw-gdb.c:(.text+0x908): undefined reference to `sof_client_ipc4_find_debug_slot_offset_by_type'

Reported-by: kernel test robot <lkp@intel.com>
Signed-off-by: Peter Ujfalusi <peter.ujfalusi@linux.intel.com>